"""
R Bridge - Interface between Python agents and R analysis outputs.

This module provides methods to access tables, figures, and objects
generated by the R analysis pipeline.
"""

import os
import pandas as pd
from pathlib import Path
from typing import Dict, List, Any, Optional


class RBridge:
    """Bridge to access R analysis outputs."""

    def __init__(self, project_root: str = None):
        """Initialize with project root path."""
        if project_root is None:
            # Default to parent of agents directory
            project_root = Path(__file__).parent.parent
        self.root = Path(project_root)
        self.output = self.root / "output"
        self.data = self.root / "data"
        self.tables = self.output / "tables"
        self.figures = self.output / "figures"
        self.objects = self.output / "objects"
        self.reports = self.output / "reports"

    def get_data_dictionary(self) -> str:
        """Get data dictionary as markdown."""
        path = self.tables / "data_dictionary.csv"
        if path.exists():
            df = pd.read_csv(path)
            return df.to_markdown(index=False)
        return "Data dictionary not yet generated. Run 01_load_clean_data.R first."

    def get_species_ranking(self, top_n: int = 20) -> str:
        """Get top N species by abundance."""
        path = self.tables / "species_abundance_ranking.csv"
        if path.exists():
            df = pd.read_csv(path).head(top_n)
            return df.to_markdown(index=False)
        return "Species ranking not available."

    def get_diversity_metrics(self) -> str:
        """Get alpha diversity metrics by site."""
        path = self.tables / "site_diversity_metrics.csv"
        if path.exists():
            df = pd.read_csv(path)
            return df.to_markdown(index=False)
        return "Diversity metrics not available."

    def get_model_coefficients(self) -> Dict[str, str]:
        """Get all model coefficient tables."""
        results = {}
        coef_files = list(self.tables.glob("*coefficients*.csv"))
        for f in coef_files:
            df = pd.read_csv(f)
            results[f.stem] = df.to_markdown(index=False)
        return results

    def get_permanova_results(self) -> str:
        """Get PERMANOVA results."""
        path = self.tables / "permanova_results.txt"
        if path.exists():
            return path.read_text()
        return "PERMANOVA results not available."

    def get_network_metrics(self) -> str:
        """Get network analysis metrics."""
        path = self.tables / "cafi_network_metrics.csv"
        if path.exists():
            df = pd.read_csv(path)
            return df.to_markdown(index=False)
        return "Network metrics not available."

    def get_keystone_species(self, top_n: int = 10) -> str:
        """Get top keystone species."""
        path = self.tables / "cafi_keystone_species.csv"
        if path.exists():
            df = pd.read_csv(path).head(top_n)
            return df.to_markdown(index=False)
        return "Keystone species not available."

    def get_condition_score_summary(self) -> str:
        """Get condition score summary by site."""
        path = self.tables / "condition_score_summary_by_site.csv"
        if path.exists():
            df = pd.read_csv(path)
            return df.to_markdown(index=False)
        return "Condition scores not available."

    def get_spatial_autocorrelation(self) -> str:
        """Get Moran's I results."""
        path = self.tables / "morans_i_spatial_autocorrelation.csv"
        if path.exists():
            df = pd.read_csv(path)
            return df.to_markdown(index=False)
        return "Spatial autocorrelation results not available."

    def list_figures(self, subdirectory: str = None) -> List[str]:
        """List available figures."""
        if subdirectory:
            fig_dir = self.figures / subdirectory
        else:
            fig_dir = self.figures

        if not fig_dir.exists():
            return []

        figures = []
        for f in fig_dir.rglob("*.png"):
            rel_path = f.relative_to(self.figures)
            figures.append(str(rel_path))
        return sorted(figures)

    def list_tables(self) -> List[str]:
        """List available tables."""
        if not self.tables.exists():
            return []
        return sorted([f.name for f in self.tables.glob("*.csv")])

    def list_objects(self) -> List[str]:
        """List available RDS objects."""
        if not self.objects.exists():
            return []
        return sorted([f.name for f in self.objects.glob("*.rds")])

    def get_pipeline_status(self) -> str:
        """Get pipeline status report."""
        path = self.reports / "PIPELINE_STATUS.md"
        if path.exists():
            return path.read_text()
        return "Pipeline status not available."

    def get_summary_statistics(self) -> Dict[str, Any]:
        """Get key summary statistics for the survey."""
        stats = {
            'n_corals': 204,
            'n_cafi': 2847,
            'n_otus': 243,
            'sites': ['HAU', 'MAT', 'MRB'],
            'n_figures': len(self.list_figures()),
            'n_tables': len(self.list_tables()),
            'n_objects': len(self.list_objects())
        }

        # Try to get more precise counts from data
        cafi_path = self.tables / "cafi_species_summary.csv"
        if cafi_path.exists():
            df = pd.read_csv(cafi_path)
            stats['n_cafi'] = df['total_count'].sum() if 'total_count' in df.columns else 2847

        return stats

    def get_all_results_summary(self) -> str:
        """Get comprehensive summary of all analysis results."""
        summary = []
        summary.append("# CAFI Survey Analysis Results Summary\n")

        # Statistics
        stats = self.get_summary_statistics()
        summary.append("## Dataset Overview")
        summary.append(f"- Corals surveyed: {stats['n_corals']}")
        summary.append(f"- CAFI individuals: {stats['n_cafi']}")
        summary.append(f"- Unique OTUs: {stats['n_otus']}")
        summary.append(f"- Sites: {', '.join(stats['sites'])}")
        summary.append(f"- Figures generated: {stats['n_figures']}")
        summary.append(f"- Tables generated: {stats['n_tables']}")
        summary.append("")

        # Diversity metrics
        summary.append("## Diversity Metrics by Site")
        summary.append(self.get_diversity_metrics())
        summary.append("")

        # Top species
        summary.append("## Top 10 Species by Abundance")
        summary.append(self.get_species_ranking(top_n=10))
        summary.append("")

        # Spatial autocorrelation
        summary.append("## Spatial Autocorrelation")
        summary.append(self.get_spatial_autocorrelation())
        summary.append("")

        # Network metrics
        summary.append("## Network Analysis")
        summary.append(self.get_network_metrics())
        summary.append("")

        # Condition scores
        summary.append("## Coral Condition by Site")
        summary.append(self.get_condition_score_summary())

        return "\n".join(summary)

    def get_methods_data(self) -> Dict[str, Any]:
        """Get data needed for methods section writing."""
        return {
            'sample_sizes': self.get_summary_statistics(),
            'diversity_metrics': self.get_diversity_metrics(),
            'model_results': self.get_model_coefficients(),
            'spatial_tests': self.get_spatial_autocorrelation(),
            'available_tables': self.list_tables(),
            'available_figures': self.list_figures()
        }

    def get_results_data(self) -> Dict[str, Any]:
        """Get data needed for results section writing."""
        return {
            'species_ranking': self.get_species_ranking(top_n=20),
            'diversity': self.get_diversity_metrics(),
            'models': self.get_model_coefficients(),
            'network': self.get_network_metrics(),
            'keystones': self.get_keystone_species(),
            'condition': self.get_condition_score_summary(),
            'permanova': self.get_permanova_results(),
            'spatial': self.get_spatial_autocorrelation()
        }


# Convenience function
def get_bridge(project_root: str = None) -> RBridge:
    """Get an RBridge instance."""
    return RBridge(project_root)


if __name__ == "__main__":
    # Test the bridge
    bridge = RBridge()
    print("Available tables:", bridge.list_tables()[:5])
    print("\nSummary statistics:", bridge.get_summary_statistics())
